(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
var GameObjectPlugin,config,create,game,preload,update;GameObjectPlugin=require("./plugin.coffee"),preload=require("./preload.coffee"),create=require("./create.coffee"),update=require("./update.coffee"),config={type:Phaser.AUTO,title:"No Bag For Evidence",width:320,height:240,pixelArt:!0,zoom:2,plugins:{global:[{key:"GameObjectPlugin",plugin:GameObjectPlugin,start:!0}]},scene:{preload:preload,create:create,update:update}},game=new Phaser.Game(config);

},{"./create.coffee":4,"./plugin.coffee":8,"./preload.coffee":9,"./update.coffee":10}],2:[function(require,module,exports){
var CUSTOM_CLASSES,GAME_OBJECTS,GameObject,StaticObject,addObjectByIndex;GameObject=require("./game_objects/game_object.coffee"),StaticObject=require("./game_objects/static_object.coffee"),CUSTOM_CLASSES={Hero:require("./game_objects/hero.coffee")},GAME_OBJECTS={1:{key:"car",static:!0},2:{key:"key"},3:{key:"hero",customClass:"Hero"},4:{key:"body"},5:{key:"bin"},6:{key:"newspapers"},7:{key:"smoker",static:!0},8:{key:"door",static:!0}},addObjectByIndex=function(e,t,i,r){var a,c;return(c=GAME_OBJECTS[t]).customClass?(a=CUSTOM_CLASSES[c.customClass])||console.error(`unknown class ${c.customClass}`):a=c.static?StaticObject:GameObject,e.add.object(a,i,r,c.key)},module.exports=function(e){var t,i,r,a,c,s,o,d,u,n,S,b,l,m;for((c=e.make.tilemap({key:"tiles",tileWidth:e.tileSize,tileHeight:e.tileSize})).createStaticLayer(0,c.addTilesetImage("tiles")),o=e.make.tilemap({key:"objects"}),e.presentGrid=[],e.futureGrid=[],m=i=0,d=c.height;0<=d?i<d:i>d;m=0<=d?++i:--i){for(t=[],l=r=0,u=c.width;0<=u?r<u:r>u;l=0<=u?++r:--r)(b=c.getTileAt(l,m))&&1===b.index?t[l]=1:t[l]=0;e.presentGrid.push(t),e.futureGrid.push([])}for(S=[],m=a=0,n=c.height;0<=n?a<n:a>n;m=0<=n?++a:--a)S.push(function(){var i,r,a;for(a=[],l=i=0,r=c.width;0<=r?i<r:i>r;l=0<=r?++i:--i)(s=o.getTileAt(l,m))?a.push(t[l]=addObjectByIndex(e,s.index,l,m)):a.push(void 0);return a}());return S};

},{"./game_objects/game_object.coffee":5,"./game_objects/hero.coffee":6,"./game_objects/static_object.coffee":7}],3:[function(require,module,exports){
var COMBINATIONS,CombinationsPlugin,GameObject;GameObject=require("./game_objects/game_object.coffee"),COMBINATIONS={key:{car:[{type:"create",item:2,key:"magnifying_glass",direction:"right"},{type:"create",item:2,key:"gun",direction:"right"},{type:"destroy",item:1}]},magnifying_glass:{body:[{type:"create",item:2,key:"hair",direction:"right"},{type:"destroy",item:1},{type:"text",text:"I got him now! \nThanks for playin!"}]},gun:{smoker:[{type:"destroy",item:2},{type:"create",item:1,key:"cigarette",direction:"right"},{type:"destroy",item:1}]},cigarette:{newspapers:[{type:"destroy",item:2},{type:"destroy",item:1}]}},CombinationsPlugin=class{constructor(e){this.scene=e}combine(e,t){var i,r,n,o,s,c,a;if(COMBINATIONS[e.id]?COMBINATIONS[e.id][t.id]&&(c=!0):COMBINATIONS[t.id]&&COMBINATIONS[t.id][e.id]&&(c=!0,a=e,e=t,t=a,c=!0),!c)return!1;for(r=0,o=(s=COMBINATIONS[e.id][t.id]).length;r<o;r++)i=s[r],n=this._targetItem(e,t,i.item),this[i.type](n,i);return!0}create(e,t){var i,r;return r=this.scene.directionToXY(t.direction,e.tilePosition.x,e.tilePosition.y),1!==this.scene.getTile(r.x,r.y)&&((i=new GameObject(this.scene,e.tilePosition.x,e.tilePosition.y,t.key)).moveTo(t.direction)?(this.scene.children.add(i),!0):(i.destroy(),!1))}destroy(e){return e.destroy()}text(e,t){var i;return(i=this.scene.add.graphics()).lineStyle(1,4095),i.fillStyle(0),i.fillRect(20,20,280,100),this.scene.add.text(30,30,t.text,{fontSize:16})}_actionPossible(e,t){var i;switch(t.type){case"create":return i=this.scene.directionToXY(t.direction,e.tilePosition.x,e.tilePosition.y),this.scene.getTile(i.x,i.y).checkMoveTo(t.direction);default:return!0}}_targetItem(e,t,i){return[e,t][i-1]}},module.exports=CombinationsPlugin;

},{"./game_objects/game_object.coffee":5}],4:[function(require,module,exports){
var CombinationsPlugin,buildMap;CombinationsPlugin=require("./combinations.coffee"),buildMap=require("./build_map.coffee"),module.exports=function(){return this.setTile=function(i,t,e){return this.presentGrid[t][i]=e},this.getTile=function(i,t){return this.presentGrid[t][i]},this.setFutureTile=function(i,t,e){return this.futureGrid[t][i]=e},this.getFutureTile=function(i,t){return this.futureGrid[t][i]},this.directionToXY=function(i,t=0,e=0){switch(i){case"up":return{x:t,y:e-1};case"down":return{x:t,y:e+1};case"left":return{x:t-1,y:e};case"right":return{x:t+1,y:e}}},this.tileSize=32,this.tileSizeHalf=this.tileSize/2,this.combinations=new CombinationsPlugin(this),buildMap(this),this.input.keyboard.on("keydown",function(i){if("r"===i.key)return this.scene.scene.restart()})};

},{"./build_map.coffee":2,"./combinations.coffee":3}],5:[function(require,module,exports){
var GameObject;GameObject=class extends Phaser.GameObjects.Image{constructor(i,t,e,s,o){super(i,t,e,s,o),this.id=s,this.combinable=!0,this.movable=!0}_checkMoveTo(i){var t,e;if(!this.movable)return!1;if(t=this.futurePosition||this.tilePosition,this.futurePosition=this.scene.directionToXY(i,t.x,t.y),e=this.scene.getFutureTile(this.futurePosition.x,this.futurePosition.y)){if(!this.combineWith(e)&&!e.moveTo(i))return!1;this.scene.setFutureTile(this.futurePosition.x,this.futurePosition.y,this)}return 1!==(e=this.scene.getTile(this.futurePosition.x,this.futurePosition.y))&&(0===e||!(!this.combineWith(e)&&!e.moveTo(i)))}moveTo(i){return this.direction=i,this._checkMoveTo(i)?(this._makeAMove(),!0):(this.futurePosition&&(this.scene.setFutureTile(this.futurePosition.x,this.futurePosition.y,void 0),this.futurePosition=void 0),!1)}_makeAMove(){if(!this.destroyed)return this.scene.setFutureTile(this.futurePosition.x,this.futurePosition.y,void 0),this.setPosition(this.futurePosition.x,this.futurePosition.y,!1),this.futurePosition=void 0}combineWith(i){if(this.combinable&&i.combinable)return this.scene.combinations.combine(this,i)}setPosition(i,t,e=!0){if(!this.destroyed)return e?(this.futurePosition={x:i,y:t},this.scene.setFutureTile(this.futurePosition.x,this.futurePosition.y,this)):(this.tilePosition&&this.scene.setTile(this.tilePosition.x,this.tilePosition.y,0),this.tilePosition={x:i,y:t},this.scene.setTile(this.tilePosition.x,this.tilePosition.y,this)),super.setPosition(i*this.scene.tileSize+this.scene.tileSizeHalf,t*this.scene.tileSize+this.scene.tileSizeHalf)}destroy(){return this.futurePosition&&this.scene.setFutureTile(this.futurePosition.x,this.futurePosition.y,void 0),this.tilePosition&&this.scene.setTile(this.tilePosition.x,this.tilePosition.y,0),this.destroyed=!0,super.destroy()}},module.exports=GameObject;

},{}],6:[function(require,module,exports){
var GameObject,Hero;GameObject=require("./game_object.coffee"),Hero=class extends GameObject{constructor(e,r,o,t,s){var a;super(e,r,o,t,s),this.combinable=!1,a=this,this.scene.input.keyboard.on("keydown",function(e){var r;if("w"===(r=e.key)||"s"===r||"a"===r||"d"===r||"ArrowUp"===r||"ArrowDown"===r||"ArrowLeft"===r||"ArrowRight"===r)switch(e.key){case"w":case"ArrowUp":return a.moveTo("up");case"s":case"ArrowDown":return a.moveTo("down");case"a":case"ArrowLeft":return a.moveTo("left");case"d":case"ArrowRight":return a.moveTo("right")}})}},module.exports=Hero;

},{"./game_object.coffee":5}],7:[function(require,module,exports){
var GameObject,StaticObject;GameObject=require("./game_object.coffee"),StaticObject=class extends GameObject{constructor(e,t,c,a,b){super(e,t,c,a,b),this.movable=!1}},module.exports=StaticObject;

},{"./game_object.coffee":5}],8:[function(require,module,exports){
var GameObjectPlugin;GameObjectPlugin=class extends Phaser.Plugins.BasePlugin{constructor(e){super(e),e.registerGameObject("object",this.createObject)}createObject(e,t,s,a,c){var r;return r=new e(this.scene,t,s,a,c),this.displayList.add(r),r._makeAMove()}},module.exports=GameObjectPlugin;

},{}],9:[function(require,module,exports){
var IMAGES;IMAGES=["hero","car","key","magnifying_glass","gun","body","hair","bin","newspapers","smoker","cigarette","door"],module.exports=function(){var e,a,i;for(e=0,i=IMAGES.length;e<i;e++)a=IMAGES[e],this.load.image(a,`images/${a}.png`);return this.load.image("tiles","images/tiles.png"),this.load.tilemapCSV("tiles","tilemaps/map_tiles.csv"),this.load.tilemapCSV("objects","tilemaps/map_objects.csv")};

},{}],10:[function(require,module,exports){
module.exports=function(){};

},{}]},{},[1]);
